### ISSUE TITLE
Integrate with claude API

### ISSUE THREAD

**Issue by kelyacf** [Deeptechia/geppetto#57]
Create a claude_handler.py similar to [gemini_handler.py](https://github.com/Deeptechia/geppetto/blob/main/geppetto/gemini_handler.py)
in order to use claude as model in geppetto too

more info 
https://www.anthropic.com/api 

https://docs.anthropic.com/en/docs/quickstart

**Comment by FedPat-CF** [comment]
## Steps
- [ ] Integrate Claude.AI
- [ ] Create LLM_claude command to switch to Claude within Geppetto 
- [ ] Add related tests in https://github.com/Deeptechia/geppetto/tree/main/tests
- [ ] Add Camila as an author in https://github.com/Deeptechia/geppetto/blob/main/pyproject.toml
