### ISSUE TITLE
New feature to let user switch between LLMs

### ISSUE THREAD

**Issue by simsbluebox** [Deeptechia/geppetto#7]
According to the new design of LLMs controller and handlers, add a new feature to let Geppetto switch between LLMs.
Two main requirements were given for this feature:
- The mechanism must be simple in the same user message (i.e. an inline keyword, hashtag, etc.)
- When switching during an ongoing conversation, the only message delivered to the new LLM would be the first interaction in the thread and the actual switcher message.

**Comment by kelyacf** [comment]
use llm_openai and llm_gemini inside the message to change LLM response model
